### ISSUE TITLE
SYSTEM | PERMISSION

### ISSUE THREAD

**Issue by jecelbi** [ictdu/sms#50]
## Task
- [ ] Assign permission to role
- [ ] Assign role to user
- [ ] Condition views and UI components based on permission

## Additional
- N/A

## Developer
- Front-end
